version: "3.8"
services:
  chatwidget:
    build: .
    container_name: chatwidget
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - TURBOPACK_DISABLE_DEV_OVERLAY=1
    restart: unless-stopped
